connect / as sysdba
create spfile from pfile;
startup nomount
CREATE DATABASE ORCL
EXTENT MANAGEMENT LOCAL
NATIONAL CHARACTER SET CL8MSWIN1251
DEFAULT TEMPORARY TABLESPACE temp
UNDO TABLESPACE undotbs1
DEFAULT TABLESPACE users;
CREATE TABLESPACE apps_tbs LOGGING 
     DATAFILE '/u01/app/oracle/oradata/ORCL/apps01.dbf' 
     SIZE 10G REUSE AUTOEXTEND ON NEXT  1280K MAXSIZE UNLIMITED
     EXTENT MANAGEMENT LOCAL;
CREATE TABLESPACE indx_tbs LOGGING 
     DATAFILE '/u01/app/oracle/oradata/ORCL/indx01.dbf' 
     SIZE 100M REUSE AUTOEXTEND ON NEXT  1280K MAXSIZE UNLIMITED 
     EXTENT MANAGEMENT LOCAL;

ALTER SYSTEM SET SGA_TARGET = 50G;
ALTER SYSTEM SET SHARED_POOL_SIZE = 5G;
ALTER SYSTEM SET LARGE_POOL_SIZE = 5G;
ALTER SYSTEM SET JAVA_POOL_SIZE = 500M;
ALTER SYSTEM SET DB_CACHE_SIZE = 35G;
ALTER SYSTEM SET STREAMS_POOL_SIZE = 5G;
exit
